project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Hands-on Exercises"
        menu: 
          - text: "1. A Layered Grammar of Graphics"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "2. Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "3a. Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "3b. Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "4a. Visualing Distributions"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "4b. Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          - text: "4c. Visualing Uncertainty"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "4d. Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
          - text: "5a. Creating Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "5b. Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
          - text: "5c. Heatmap for Visualising and Analysing Multivariate Data"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
          - text: "5d. Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
          - text: "5e. Treemap Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
          - text: "6. Visualising and Analysing Time-oriented Data"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "7a. Choropleth Mapping with R"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html"
          - text: "7b. Visualising Geospatial Point Data"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html"
          - text: "7c. Analytical Mapping"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07c.html"
          - text: "8. Modelling, Visualising and Analysing Network Data"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"    
          - text: "9. Information Dashboard Design"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html" 
      - text: "In-class Exercises"
        menu: 
          - text: "1. Now you see it!"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "2. Tableau Hands-on Part 1"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "3. Tableau Hands-on Part 2"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "4. Recap on interactivity"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "5. Build a Shiny App"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "6. Time series charts"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "7a. Geospatial maps in Tableau"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07a.html"
          - text: "7b. Geospatial maps in R"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07b.html"
          - text: "9. Tableau - Bullet and Sparkline"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
      - text: "Take-home Exercises"
        menu: 
          - text: "1. PISA Singapore 2022"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "2. Data Visualisation Makeover"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "3. Be Weatherwise Or Otherwise"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
          - text: "4. Prototyping Modules for Shiny Application"
            href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
      - text: "Project"
        href: "https://merrycheesecake-isss608.netlify.app/"
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual